syntax on

set background=dark

" Search down into subfolders
" Provides tab-completion for all file-related tasks
set path+=**

" Display all matching files when we tab complete"
set wildmenu

filetype plugin on
set omnifunc=syntaxcomplete#Complete

"nnoremap <C-f> "xyiw:exe "grep --color -rn ".@x." ."<CR>
"nnoremap <C-f> :exe '!grep --color --exclude-from=.gitignore -rn ' . shellescape(expand('<cfile>'), 1) . " . "
"nnoremap <C-f> "xyiw:grep -rn --exclude=tags ".@x." ."

command! -nargs=+ Grep execute 'silent grep! -I -r -n --exclude tags . -e <args>' | copen | execute 'silent /<args>'
nnoremap <C-f> :Grep <c-r>=expand("<cword>")<cr><cr>

" Create the `tags` file (may need to install ctags first)
" sudo apt-get install universal-ctags
command! MakeTags !ctags -R .
" NOW WE CAN:
" - Use ^] to jump to tag under cursor
" - Use g^] for ambiguous tags
" - Use ^t to jump back up the tag stack

" Tweaks for browsing
let g:netrw_banner=0        " disable annoying banner
"let g:netrw_browse_split=4  " open in prior window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
"let g:netrw_list_hide=netrw_gitignore#Hide()
"let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'

" line num
set nu

" highlight ending spaces
highlight ExtraWhitespace ctermbg=DarkBlue
call matchadd('ExtraWhitespace', '\s\+$')
" highlight 81th char
highlight OverLength ctermbg=DarkRed ctermfg=White
call matchadd('OverLength', '\%81v.')


set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set smartindent
set smarttab
set autoindent
retab

set list
set listchars=tab:>\|

" keep selection on (un)indent with < and >
vmap > >gv
vmap < <gv
" keep selection on (un)indent with <Tab> and <S-Tab>
vmap <Tab> >gv
vmap <S-TAB> <gv
" keep selection on delete
vmap x xgv
" visual insertion
vmap i I
" visual append
vmap a A

" tab shortcuts
nnoremap tt  :tabedit .<CR>
nnoremap tj  :tabnext<CR>
nnoremap tk  :tabprev<CR>

" set markdown textwith to 80 (:gq to rewrap)
au BufRead,BufNewFile *.md setlocal textwidth=80


" uft8 symbols
ab :forall: ∀
ab :exist: ∃
ab :exists: ∃
ab :notexist: ∄
ab :notexists: ∄
ab :in: ∈
ab :notin: ∉
ab :not: ¬
ab :true: ⊤
ab :false: ⟂
ab :empty: ∅
ab :infty: ∞
ab :infinity: ∞
ab :and: ∧
ab :or: ∨
ab :N: ℕ
ab :Z: ℤ
ab :Q: ℚ
ab :F: 𝔽
ab :R: ℝ
ab :C: ℂ
ab :K: 𝕂
ab :U: 𝕌
ab :inter: ⋂
ab :union: ⋃
ab :cap: ⋂
ab :cup: ⋃
ab :subset: ⊂
ab :superset: ⊃
ab :to: →
ab :from: ←
ab :larr: ←
ab :rarr: →
ab :uarr: ↑
ab :darr: ↓
ab :harr: ↔
ab :mapsto: ↦
ab :impliedby: ⇐
ab :implied: ⇐
ab :implies: ⇒
ab :imply: ⇒
ab :iff: ⇔
ab :sum: Σ
ab :prod: ∏
ab :int: ∫
ab :times: ×
ab :pm: ±
ab :mod: ≡
ab :equiv: ≡
ab :neq: ≠
ab :simeq: ≈
ab :approx: ≈
ab :lte: ≤
ab :gte: ≥
ab :sqrt: √
ab :3root: ∛
ab :4root: ∜
ab :partial: ∂
ab :dot: ⋅
"∘ ⋆ ⟡ ⋄
ab :[: ⟦
ab :]: ⟧
ab :(: ⟨
ab :): ⟩
ab :ceil[: ⌈
ab :ceil]: ⌉
ab :floor[: ⌊
ab :floor]: ⌋
"ab :|: ⋮
"ab :-: ⋯
"ab :/: ⋰
"ab :\: ⋱
ab :cqfd: ∎
ab :^0: ⁰
ab :^1: ¹
ab :^2: ²
ab :^3: ³
ab :^4: ⁴
ab :^5: ⁵
ab :^6: ⁶
ab :^7: ⁷
ab :^8: ⁸
ab :^9: ⁹
ab :^+: ⁺
ab :^-: ⁻
ab :^=: ⁼
ab :^(: ⁽
ab :^): ⁾
ab :^n: ⁿ
ab :^i: ⁱ
ab :_0: ₀
ab :_1: ₁
ab :_2: ₂
ab :_3: ₃
ab :_4: ₄
ab :_5: ₅
ab :_6: ₆
ab :_7: ₇
ab :_8: ₈
ab :_9: ₉
ab :_+: ₊
ab :_-: ₋
ab :_=: ₌
ab :_(: ₍
ab :_): ₎
ab :_n: ₙ
ab :_i: ᵢ
ab :_a: ₐ
ab :_e: ₑ
ab :_h: ₕ
ab :_j: ⱼ
ab :_k: ₖ
ab :_l: ₗ
ab :_m: ₘ
ab :_o: ₒ
ab :_p: ₚ
ab :_r: ᵣ
ab :_s: ₛ
ab :_t: ₜ
ab :_u: ᵤ
ab :_v: ᵥ
ab :_x: ₓ
ab :i: 𝒾
ab :j: 𝒿
ab :e: ℯ
ab :l: ℓ
"ℜ ℑ ℵ Ϝ ϝ
"⊕ ⊖ ⊗ ⊘ ⊙ ⊚ ⊛ ⊜ ⊝
"Α Β Γ Δ Ε Ζ Η Θ Ι Κ Λ Μ Ν Ξ Ο Π Ρ Σ Τ Υ Φ Χ Ψ Ω
ab :Alpha:      Α
ab :Beta:       Β
ab :Gamma:      Γ
ab :Delta:      Δ
ab :Epsilon:    Ε
ab :Zeta:       Ζ
ab :Eta:        Η
ab :Theta:      Θ
ab :Iota:       Ι
ab :Kappa:      Κ
ab :Lambda:     Λ
ab :Mu:         Μ
ab :Nu:         Ν
ab :Ksi:        Ξ
ab :Xi:         Ξ
ab :Omicron:    Ο
ab :Pi:         Π
ab :Ro:         Ρ
ab :Sigma:      Σ
ab :Tau:        Τ
ab :Upsilon:    Υ
ab :Phi:        Φ
ab :Khi:        Χ
ab :Chi:        Χ
ab :Psi:        Ψ
ab :Omega:      Ω

ab :alpha:      α
ab :beta:       β
ab :gamma:      γ
ab :delta:      δ
ab :epsilon:    ε
ab :zeta:       ζ
ab :eta:        η
ab :theta:      θ
ab :iota:       ι
ab :kappa:      κ
ab :lambda:     λ
ab :mu:         μ
ab :nu:         ν
ab :ksi:        ξ
ab :xi:         ξ
ab :omicron:    ο
ab :pi:         π
ab :ro:         ρ
ab :sigma:      σ
ab :tau:        τ
ab :upsilon:    υ
ab :phi:        φ
ab :phi':       ϕ
ab :khi:        χ
ab :chi:        χ
ab :psi:        ψ
ab :omega:      ω

ab :necessity: □
ab :necessary: □
ab :possible: ◇

ab :flat: ♭
ab :sharp: ♯


" Emoji shortcuts
ab :ambulance: 🚑
ab :art: 🎨
ab :blood: 🩸 
ab :bomb: 💣
ab :book: 📖
ab :bug: 🐛
ab :bulb: 💡
ab :computer: 💻
ab :construction: 🚧
ab :elephant: 🐘
ab :email: 📧
ab :gear: ⚙️ 
ab :info: ℹ️
ab :label: 🏷️
ab :link: 🔗
ab :memo: 📝
ab :ninja: 🥷
ab :nut_and_bolt: 🔩
ab :package: 📦
ab :pencil: 📝
ab :pill: 💊
ab :point_right: 👉
ab :pushpin: 📌
ab :rabbit: 🐰
ab :recycle: ♻️
ab :rocket: 🚀
ab :shell: 🐚
ab :snake: 🐍
ab :tada: 🎉
ab :telephone: 📞
ab :test_tube: 🧪
ab :ticket: 🎫
ab :troll: 🧌
ab :up: 🆙
ab :vampire: 🧛
ab :warning: ⚠️
ab :whale: 🐋
ab :white_check_mark: ✅
ab :wrench: 🔧
ab :yarn: 🧶
ab :zombie: 🧟
ab :fuck: 🖕
ab :mage: 🧙
ab :wizard: 🧙

ab :hash: #️⃣
ab :keycap_star: *️⃣
ab :zero: 0️⃣
ab :one: 1️⃣
ab :two: 2️⃣
ab :three: 3️⃣
ab :four: 4️⃣
ab :five: 5️⃣
ab :six: 6️⃣
ab :seven: 7️⃣
ab :eight: 8️⃣
ab :nine: 9️⃣
ab :copyright: ©️
ab :registered: ®️
ab :mahjong: 🀄
ab :black_joker: 🃏
ab :a: 🅰️
ab :b: 🅱️
ab :o2: 🅾️
ab :parking: 🅿️
ab :ab: 🆎
ab :cl: 🆑
ab :cool: 🆒
ab :free: 🆓
ab :id: 🆔
ab :new: 🆕
ab :ng: 🆖
ab :ok: 🆗
ab :sos: 🆘
ab :up: 🆙
ab :vs: 🆚
ab :flag-ac: 🇦🇨
ab :flag-ad: 🇦🇩
ab :flag-ae: 🇦🇪
ab :flag-af: 🇦🇫
ab :flag-ag: 🇦🇬
ab :flag-ai: 🇦🇮
ab :flag-al: 🇦🇱
ab :flag-am: 🇦🇲
ab :flag-ao: 🇦🇴
ab :flag-aq: 🇦🇶
ab :flag-ar: 🇦🇷
ab :flag-as: 🇦🇸
ab :flag-at: 🇦🇹
ab :flag-au: 🇦🇺
ab :flag-aw: 🇦🇼
ab :flag-ax: 🇦🇽
ab :flag-az: 🇦🇿
ab :flag-ba: 🇧🇦
ab :flag-bb: 🇧🇧
ab :flag-bd: 🇧🇩
ab :flag-be: 🇧🇪
ab :flag-bf: 🇧🇫
ab :flag-bg: 🇧🇬
ab :flag-bh: 🇧🇭
ab :flag-bi: 🇧🇮
ab :flag-bj: 🇧🇯
ab :flag-bl: 🇧🇱
ab :flag-bm: 🇧🇲
ab :flag-bn: 🇧🇳
ab :flag-bo: 🇧🇴
ab :flag-bq: 🇧🇶
ab :flag-br: 🇧🇷
ab :flag-bs: 🇧🇸
ab :flag-bt: 🇧🇹
ab :flag-bv: 🇧🇻
ab :flag-bw: 🇧🇼
ab :flag-by: 🇧🇾
ab :flag-bz: 🇧🇿
ab :flag-ca: 🇨🇦
ab :flag-cc: 🇨🇨
ab :flag-cd: 🇨🇩
ab :flag-cf: 🇨🇫
ab :flag-cg: 🇨🇬
ab :flag-ch: 🇨🇭
ab :flag-ci: 🇨🇮
ab :flag-ck: 🇨🇰
ab :flag-cl: 🇨🇱
ab :flag-cm: 🇨🇲
ab :cn: 🇨🇳
ab :flag-co: 🇨🇴
ab :flag-cp: 🇨🇵
ab :flag-cr: 🇨🇷
ab :flag-cu: 🇨🇺
ab :flag-cv: 🇨🇻
ab :flag-cw: 🇨🇼
ab :flag-cx: 🇨🇽
ab :flag-cy: 🇨🇾
ab :flag-cz: 🇨🇿
ab :de: 🇩🇪
ab :flag-dg: 🇩🇬
ab :flag-dj: 🇩🇯
ab :flag-dk: 🇩🇰
ab :flag-dm: 🇩🇲
ab :flag-do: 🇩🇴
ab :flag-dz: 🇩🇿
ab :flag-ea: 🇪🇦
ab :flag-ec: 🇪🇨
ab :flag-ee: 🇪🇪
ab :flag-eg: 🇪🇬
ab :flag-eh: 🇪🇭
ab :flag-er: 🇪🇷
ab :es: 🇪🇸
ab :flag-et: 🇪🇹
ab :flag-eu: 🇪🇺
ab :flag-fi: 🇫🇮
ab :flag-fj: 🇫🇯
ab :flag-fk: 🇫🇰
ab :flag-fm: 🇫🇲
ab :flag-fo: 🇫🇴
ab :fr: 🇫🇷
ab :flag-ga: 🇬🇦
ab :gb: 🇬🇧
ab :flag-gd: 🇬🇩
ab :flag-ge: 🇬🇪
ab :flag-gf: 🇬🇫
ab :flag-gg: 🇬🇬
ab :flag-gh: 🇬🇭
ab :flag-gi: 🇬🇮
ab :flag-gl: 🇬🇱
ab :flag-gm: 🇬🇲
ab :flag-gn: 🇬🇳
ab :flag-gp: 🇬🇵
ab :flag-gq: 🇬🇶
ab :flag-gr: 🇬🇷
ab :flag-gs: 🇬🇸
ab :flag-gt: 🇬🇹
ab :flag-gu: 🇬🇺
ab :flag-gw: 🇬🇼
ab :flag-gy: 🇬🇾
ab :flag-hk: 🇭🇰
ab :flag-hm: 🇭🇲
ab :flag-hn: 🇭🇳
ab :flag-hr: 🇭🇷
ab :flag-ht: 🇭🇹
ab :flag-hu: 🇭🇺
ab :flag-ic: 🇮🇨
ab :flag-id: 🇮🇩
ab :flag-ie: 🇮🇪
ab :flag-il: 🇮🇱
ab :flag-im: 🇮🇲
ab :flag-in: 🇮🇳
ab :flag-io: 🇮🇴
ab :flag-iq: 🇮🇶
ab :flag-ir: 🇮🇷
ab :flag-is: 🇮🇸
ab :it: 🇮🇹
ab :flag-je: 🇯🇪
ab :flag-jm: 🇯🇲
ab :flag-jo: 🇯🇴
ab :jp: 🇯🇵
ab :flag-ke: 🇰🇪
ab :flag-kg: 🇰🇬
ab :flag-kh: 🇰🇭
ab :flag-ki: 🇰🇮
ab :flag-km: 🇰🇲
ab :flag-kn: 🇰🇳
ab :flag-kp: 🇰🇵
ab :kr: 🇰🇷
ab :flag-kw: 🇰🇼
ab :flag-ky: 🇰🇾
ab :flag-kz: 🇰🇿
ab :flag-la: 🇱🇦
ab :flag-lb: 🇱🇧
ab :flag-lc: 🇱🇨
ab :flag-li: 🇱🇮
ab :flag-lk: 🇱🇰
ab :flag-lr: 🇱🇷
ab :flag-ls: 🇱🇸
ab :flag-lt: 🇱🇹
ab :flag-lu: 🇱🇺
ab :flag-lv: 🇱🇻
ab :flag-ly: 🇱🇾
ab :flag-ma: 🇲🇦
ab :flag-mc: 🇲🇨
ab :flag-md: 🇲🇩
ab :flag-me: 🇲🇪
ab :flag-mf: 🇲🇫
ab :flag-mg: 🇲🇬
ab :flag-mh: 🇲🇭
ab :flag-mk: 🇲🇰
ab :flag-ml: 🇲🇱
ab :flag-mm: 🇲🇲
ab :flag-mn: 🇲🇳
ab :flag-mo: 🇲🇴
ab :flag-mp: 🇲🇵
ab :flag-mq: 🇲🇶
ab :flag-mr: 🇲🇷
ab :flag-ms: 🇲🇸
ab :flag-mt: 🇲🇹
ab :flag-mu: 🇲🇺
ab :flag-mv: 🇲🇻
ab :flag-mw: 🇲🇼
ab :flag-mx: 🇲🇽
ab :flag-my: 🇲🇾
ab :flag-mz: 🇲🇿
ab :flag-na: 🇳🇦
ab :flag-nc: 🇳🇨
ab :flag-ne: 🇳🇪
ab :flag-nf: 🇳🇫
ab :flag-ng: 🇳🇬
ab :flag-ni: 🇳🇮
ab :flag-nl: 🇳🇱
ab :flag-no: 🇳🇴
ab :flag-np: 🇳🇵
ab :flag-nr: 🇳🇷
ab :flag-nu: 🇳🇺
ab :flag-nz: 🇳🇿
ab :flag-om: 🇴🇲
ab :flag-pa: 🇵🇦
ab :flag-pe: 🇵🇪
ab :flag-pf: 🇵🇫
ab :flag-pg: 🇵🇬
ab :flag-ph: 🇵🇭
ab :flag-pk: 🇵🇰
ab :flag-pl: 🇵🇱
ab :flag-pm: 🇵🇲
ab :flag-pn: 🇵🇳
ab :flag-pr: 🇵🇷
ab :flag-ps: 🇵🇸
ab :flag-pt: 🇵🇹
ab :flag-pw: 🇵🇼
ab :flag-py: 🇵🇾
ab :flag-qa: 🇶🇦
ab :flag-re: 🇷🇪
ab :flag-ro: 🇷🇴
ab :flag-rs: 🇷🇸
ab :ru: 🇷🇺
ab :flag-rw: 🇷🇼
ab :flag-sa: 🇸🇦
ab :flag-sb: 🇸🇧
ab :flag-sc: 🇸🇨
ab :flag-sd: 🇸🇩
ab :flag-se: 🇸🇪
ab :flag-sg: 🇸🇬
ab :flag-sh: 🇸🇭
ab :flag-si: 🇸🇮
ab :flag-sj: 🇸🇯
ab :flag-sk: 🇸🇰
ab :flag-sl: 🇸🇱
ab :flag-sm: 🇸🇲
ab :flag-sn: 🇸🇳
ab :flag-so: 🇸🇴
ab :flag-sr: 🇸🇷
ab :flag-ss: 🇸🇸
ab :flag-st: 🇸🇹
ab :flag-sv: 🇸🇻
ab :flag-sx: 🇸🇽
ab :flag-sy: 🇸🇾
ab :flag-sz: 🇸🇿
ab :flag-ta: 🇹🇦
ab :flag-tc: 🇹🇨
ab :flag-td: 🇹🇩
ab :flag-tf: 🇹🇫
ab :flag-tg: 🇹🇬
ab :flag-th: 🇹🇭
ab :flag-tj: 🇹🇯
ab :flag-tk: 🇹🇰
ab :flag-tl: 🇹🇱
ab :flag-tm: 🇹🇲
ab :flag-tn: 🇹🇳
ab :flag-to: 🇹🇴
ab :flag-tr: 🇹🇷
ab :flag-tt: 🇹🇹
ab :flag-tv: 🇹🇻
ab :flag-tw: 🇹🇼
ab :flag-tz: 🇹🇿
ab :flag-ua: 🇺🇦
ab :flag-ug: 🇺🇬
ab :flag-um: 🇺🇲
ab :flag-un: 🇺🇳
ab :us: 🇺🇸
ab :flag-uy: 🇺🇾
ab :flag-uz: 🇺🇿
ab :flag-va: 🇻🇦
ab :flag-vc: 🇻🇨
ab :flag-ve: 🇻🇪
ab :flag-vg: 🇻🇬
ab :flag-vi: 🇻🇮
ab :flag-vn: 🇻🇳
ab :flag-vu: 🇻🇺
ab :flag-wf: 🇼🇫
ab :flag-ws: 🇼🇸
ab :flag-xk: 🇽🇰
ab :flag-ye: 🇾🇪
ab :flag-yt: 🇾🇹
ab :flag-za: 🇿🇦
ab :flag-zm: 🇿🇲
ab :flag-zw: 🇿🇼
ab :koko: 🈁
ab :sa: 🈂️
ab :u7121: 🈚
ab :u6307: 🈯
ab :u7981: 🈲
ab :u7a7a: 🈳
ab :u5408: 🈴
ab :u6e80: 🈵
ab :u6709: 🈶
ab :u6708: 🈷️
ab :u7533: 🈸
ab :u5272: 🈹
ab :u55b6: 🈺
ab :ideograph_advantage: 🉐
ab :accept: 🉑
ab :cyclone: 🌀
ab :foggy: 🌁
ab :closed_umbrella: 🌂
ab :night_with_stars: 🌃
ab :sunrise_over_mountains: 🌄
ab :sunrise: 🌅
ab :city_sunset: 🌆
ab :city_sunrise: 🌇
ab :rainbow: 🌈
ab :bridge_at_night: 🌉
ab :ocean: 🌊
ab :volcano: 🌋
ab :milky_way: 🌌
ab :earth_africa: 🌍
ab :earth_americas: 🌎
ab :earth_asia: 🌏
ab :globe_with_meridians: 🌐
ab :new_moon: 🌑
ab :waxing_crescent_moon: 🌒
ab :first_quarter_moon: 🌓
ab :moon: 🌔
ab :full_moon: 🌕
ab :waning_gibbous_moon: 🌖
ab :last_quarter_moon: 🌗
ab :waning_crescent_moon: 🌘
ab :crescent_moon: 🌙
ab :new_moon_with_face: 🌚
ab :first_quarter_moon_with_face: 🌛
ab :last_quarter_moon_with_face: 🌜
ab :full_moon_with_face: 🌝
ab :sun_with_face: 🌞
ab :star2: 🌟
ab :stars: 🌠
ab :thermometer: 🌡️
ab :mostly_sunny: 🌤️
ab :barely_sunny: 🌥️
ab :partly_sunny_rain: 🌦️
ab :rain_cloud: 🌧️
ab :snow_cloud: 🌨️
ab :lightning: 🌩️
ab :tornado: 🌪️
ab :fog: 🌫️
ab :wind_blowing_face: 🌬️
ab :hotdog: 🌭
ab :taco: 🌮
ab :burrito: 🌯
ab :chestnut: 🌰
ab :seedling: 🌱
ab :evergreen_tree: 🌲
ab :deciduous_tree: 🌳
ab :palm_tree: 🌴
ab :cactus: 🌵
ab :hot_pepper: 🌶️
ab :tulip: 🌷
ab :cherry_blossom: 🌸
ab :rose: 🌹
ab :hibiscus: 🌺
ab :sunflower: 🌻
ab :blossom: 🌼
ab :corn: 🌽
ab :ear_of_rice: 🌾
ab :herb: 🌿
ab :four_leaf_clover: 🍀
ab :maple_leaf: 🍁
ab :fallen_leaf: 🍂
ab :leaves: 🍃
ab :mushroom: 🍄
ab :tomato: 🍅
ab :eggplant: 🍆
ab :grapes: 🍇
ab :melon: 🍈
ab :watermelon: 🍉
ab :tangerine: 🍊
ab :lemon: 🍋
ab :banana: 🍌
ab :pineapple: 🍍
ab :apple: 🍎
ab :green_apple: 🍏
ab :pear: 🍐
ab :peach: 🍑
ab :cherries: 🍒
ab :strawberry: 🍓
ab :hamburger: 🍔
ab :pizza: 🍕
ab :meat_on_bone: 🍖
ab :poultry_leg: 🍗
ab :rice_cracker: 🍘
ab :rice_ball: 🍙
ab :rice: 🍚
ab :curry: 🍛
ab :ramen: 🍜
ab :spaghetti: 🍝
ab :bread: 🍞
ab :fries: 🍟
ab :sweet_potato: 🍠
ab :dango: 🍡
ab :oden: 🍢
ab :sushi: 🍣
ab :fried_shrimp: 🍤
ab :fish_cake: 🍥
ab :icecream: 🍦
ab :shaved_ice: 🍧
ab :ice_cream: 🍨
ab :doughnut: 🍩
ab :cookie: 🍪
ab :chocolate_bar: 🍫
ab :candy: 🍬
ab :lollipop: 🍭
ab :custard: 🍮
ab :honey_pot: 🍯
ab :cake: 🍰
ab :bento: 🍱
ab :stew: 🍲
ab :fried_egg: 🍳
ab :fork_and_knife: 🍴
ab :tea: 🍵
ab :sake: 🍶
ab :wine_glass: 🍷
ab :cocktail: 🍸
ab :tropical_drink: 🍹
ab :beer: 🍺
ab :beers: 🍻
ab :baby_bottle: 🍼
ab :knife_fork_plate: 🍽️
ab :champagne: 🍾
ab :popcorn: 🍿
ab :ribbon: 🎀
ab :gift: 🎁
ab :birthday: 🎂
ab :jack_o_lantern: 🎃
ab :christmas_tree: 🎄
ab :santa: 🎅
ab :fireworks: 🎆
ab :sparkler: 🎇
ab :balloon: 🎈
ab :tada: 🎉
ab :confetti_ball: 🎊
ab :tanabata_tree: 🎋
ab :crossed_flags: 🎌
ab :bamboo: 🎍
ab :dolls: 🎎
ab :flags: 🎏
ab :wind_chime: 🎐
ab :rice_scene: 🎑
ab :school_satchel: 🎒
ab :mortar_board: 🎓
ab :medal: 🎖️
ab :reminder_ribbon: 🎗️
ab :studio_microphone: 🎙️
ab :level_slider: 🎚️
ab :control_knobs: 🎛️
ab :film_frames: 🎞️
ab :admission_tickets: 🎟️
ab :carousel_horse: 🎠
ab :ferris_wheel: 🎡
ab :roller_coaster: 🎢
ab :fishing_pole_and_fish: 🎣
ab :microphone: 🎤
ab :movie_camera: 🎥
ab :cinema: 🎦
ab :headphones: 🎧
ab :art: 🎨
ab :tophat: 🎩
ab :circus_tent: 🎪
ab :ticket: 🎫
ab :clapper: 🎬
ab :performing_arts: 🎭
ab :video_game: 🎮
ab :dart: 🎯
ab :slot_machine: 🎰
ab :8ball: 🎱
ab :game_die: 🎲
ab :bowling: 🎳
ab :flower_playing_cards: 🎴
ab :musical_note: 🎵
ab :notes: 🎶
ab :saxophone: 🎷
ab :guitar: 🎸
ab :musical_keyboard: 🎹
ab :trumpet: 🎺
ab :violin: 🎻
ab :musical_score: 🎼
ab :running_shirt_with_sash: 🎽
ab :tennis: 🎾
ab :ski: 🎿
ab :basketball: 🏀
ab :checkered_flag: 🏁
ab :snowboarder: 🏂
ab :runner: 🏃
ab :surfer: 🏄
ab :sports_medal: 🏅
ab :trophy: 🏆
ab :horse_racing: 🏇
ab :football: 🏈
ab :rugby_football: 🏉
ab :swimmer: 🏊
ab :weight_lifter: 🏋️
ab :golfer: 🏌️
ab :racing_motorcycle: 🏍️
ab :racing_car: 🏎️
ab :cricket_bat_and_ball: 🏏
ab :volleyball: 🏐
ab :field_hockey_stick_and_ball: 🏑
ab :ice_hockey_stick_and_puck: 🏒
ab :table_tennis_paddle_and_ball: 🏓
ab :snow_capped_mountain: 🏔️
ab :camping: 🏕️
ab :beach_with_umbrella: 🏖️
ab :building_construction: 🏗️
ab :house_buildings: 🏘️
ab :cityscape: 🏙️
ab :derelict_house_building: 🏚️
ab :classical_building: 🏛️
ab :desert: 🏜️
ab :desert_island: 🏝️
ab :national_park: 🏞️
ab :stadium: 🏟️
ab :house: 🏠
ab :house_with_garden: 🏡
ab :office: 🏢
ab :post_office: 🏣
ab :european_post_office: 🏤
ab :hospital: 🏥
ab :bank: 🏦
ab :atm: 🏧
ab :hotel: 🏨
ab :love_hotel: 🏩
ab :convenience_store: 🏪
ab :school: 🏫
ab :department_store: 🏬
ab :factory: 🏭
ab :izakaya_lantern: 🏮
ab :japanese_castle: 🏯
ab :european_castle: 🏰
ab :rainbow-flag: 🏳️‍🌈
ab :transgender_flag: 🏳️‍⚧️
ab :waving_white_flag: 🏳️
ab :pirate_flag: 🏴‍☠️
ab :flag-england: 🏴󠁧󠁢󠁥󠁮󠁧󠁿
ab :flag-scotland: 🏴󠁧󠁢󠁳󠁣󠁴󠁿
ab :flag-wales: 🏴󠁧󠁢󠁷󠁬󠁳󠁿
ab :waving_black_flag: 🏴
ab :rosette: 🏵️
ab :label: 🏷️
ab :badminton_racquet_and_shuttlecock: 🏸
ab :bow_and_arrow: 🏹
ab :amphora: 🏺
ab :skin-tone-2: 🏻
ab :skin-tone-3: 🏼
ab :skin-tone-4: 🏽
ab :skin-tone-5: 🏾
ab :skin-tone-6: 🏿
ab :rat: 🐀
ab :mouse2: 🐁
ab :ox: 🐂
ab :water_buffalo: 🐃
ab :cow2: 🐄
ab :tiger2: 🐅
ab :leopard: 🐆
ab :rabbit2: 🐇
ab :cat2: 🐈
ab :dragon: 🐉
ab :crocodile: 🐊
ab :whale2: 🐋
ab :snail: 🐌
ab :snake: 🐍
ab :racehorse: 🐎
ab :ram: 🐏
ab :goat: 🐐
ab :sheep: 🐑
ab :monkey: 🐒
ab :rooster: 🐓
ab :chicken: 🐔
ab :dog2: 🐕
ab :pig2: 🐖
ab :boar: 🐗
ab :elephant: 🐘
ab :octopus: 🐙
ab :shell: 🐚
ab :bug: 🐛
ab :ant: 🐜
ab :bee: 🐝
ab :ladybug: 🐞
ab :fish: 🐟
ab :tropical_fish: 🐠
ab :blowfish: 🐡
ab :turtle: 🐢
ab :hatching_chick: 🐣
ab :baby_chick: 🐤
ab :hatched_chick: 🐥
ab :bird: 🐦
ab :penguin: 🐧
ab :koala: 🐨
ab :poodle: 🐩
ab :dromedary_camel: 🐪
ab :camel: 🐫
ab :dolphin: 🐬
ab :mouse: 🐭
ab :cow: 🐮
ab :tiger: 🐯
ab :rabbit: 🐰
ab :cat: 🐱
ab :dragon_face: 🐲
ab :whale: 🐳
ab :horse: 🐴
ab :monkey_face: 🐵
ab :dog: 🐶
ab :pig: 🐷
ab :frog: 🐸
ab :hamster: 🐹
ab :wolf: 🐺
ab :bear: 🐻
ab :panda_face: 🐼
ab :pig_nose: 🐽
ab :feet: 🐾
ab :chipmunk: 🐿️
ab :eyes: 👀
ab :eye: 👁️
ab :ear: 👂
ab :nose: 👃
ab :lips: 👄
ab :tongue: 👅
ab :point_up_2: 👆
ab :point_down: 👇
ab :point_left: 👈
ab :point_right: 👉
ab :facepunch: 👊
ab :wave: 👋
ab :ok_hand: 👌
ab :+1: 👍
ab :-1: 👎
ab :clap: 👏
ab :open_hands: 👐
ab :crown: 👑
ab :womans_hat: 👒
ab :eyeglasses: 👓
ab :necktie: 👔
ab :shirt: 👕
ab :jeans: 👖
ab :dress: 👗
ab :kimono: 👘
ab :bikini: 👙
ab :womans_clothes: 👚
ab :purse: 👛
ab :handbag: 👜
ab :pouch: 👝
ab :mans_shoe: 👞
ab :athletic_shoe: 👟
ab :high_heel: 👠
ab :sandal: 👡
ab :boot: 👢
ab :footprints: 👣
ab :bust_in_silhouette: 👤
ab :busts_in_silhouette: 👥
ab :boy: 👦
ab :girl: 👧
ab :man: 👨
ab :woman: 👩
ab :family: 👪
ab :two_men_holding_hands: 👬
ab :two_women_holding_hands: 👭
ab :cop: 👮
ab :dancers: 👯
ab :bride_with_veil: 👰
ab :person_with_blond_hair: 👱
ab :baby: 👶
ab :construction_worker: 👷
ab :princess: 👸
ab :japanese_ogre: 👹
ab :japanese_goblin: 👺
ab :ghost: 👻
ab :angel: 👼
ab :alien: 👽
ab :space_invader: 👾
ab :imp: 👿
ab :skull: 💀
ab :information_desk_person: 💁
ab :guardsman: 💂
ab :dancer: 💃
ab :lipstick: 💄
ab :nail_care: 💅
ab :massage: 💆
ab :haircut: 💇
ab :barber: 💈
ab :syringe: 💉
ab :pill: 💊
ab :kiss: 💋
ab :love_letter: 💌
ab :ring: 💍
ab :gem: 💎
ab :couplekiss: 💏
ab :bouquet: 💐
ab :couple_with_heart: 💑
ab :wedding: 💒
ab :heartbeat: 💓
ab :broken_heart: 💔
ab :two_hearts: 💕
ab :sparkling_heart: 💖
ab :heartpulse: 💗
ab :cupid: 💘
ab :blue_heart: 💙
ab :green_heart: 💚
ab :yellow_heart: 💛
ab :purple_heart: 💜
ab :gift_heart: 💝
ab :revolving_hearts: 💞
ab :heart_decoration: 💟
ab :diamond_shape_with_a_dot_inside: 💠
ab :bulb: 💡
ab :anger: 💢
ab :bomb: 💣
ab :zzz: 💤
ab :boom: 💥
ab :sweat_drops: 💦
ab :droplet: 💧
ab :dash: 💨
ab :hankey: 💩
ab :muscle: 💪
ab :dizzy: 💫
ab :speech_balloon: 💬
ab :thought_balloon: 💭
ab :white_flower: 💮
ab :100: 💯
ab :moneybag: 💰
ab :currency_exchange: 💱
ab :heavy_dollar_sign: 💲
ab :credit_card: 💳
ab :yen: 💴
ab :dollar: 💵
ab :euro: 💶
ab :pound: 💷
ab :money_with_wings: 💸
ab :chart: 💹
ab :seat: 💺
ab :computer: 💻
ab :briefcase: 💼
ab :minidisc: 💽
ab :floppy_disk: 💾
ab :cd: 💿
ab :dvd: 📀
ab :file_folder: 📁
ab :open_file_folder: 📂
ab :page_with_curl: 📃
ab :page_facing_up: 📄
ab :date: 📅
ab :calendar: 📆
ab :card_index: 📇
ab :chart_with_upwards_trend: 📈
ab :chart_with_downwards_trend: 📉
ab :bar_chart: 📊
ab :clipboard: 📋
ab :pushpin: 📌
ab :round_pushpin: 📍
ab :paperclip: 📎
ab :straight_ruler: 📏
ab :triangular_ruler: 📐
ab :bookmark_tabs: 📑
ab :ledger: 📒
ab :notebook: 📓
ab :notebook_with_decorative_cover: 📔
ab :closed_book: 📕
ab :book: 📖
ab :green_book: 📗
ab :blue_book: 📘
ab :orange_book: 📙
ab :books: 📚
ab :name_badge: 📛
ab :scroll: 📜
ab :memo: 📝
ab :telephone_receiver: 📞
ab :pager: 📟
ab :fax: 📠
ab :satellite_antenna: 📡
ab :loudspeaker: 📢
ab :mega: 📣
ab :outbox_tray: 📤
ab :inbox_tray: 📥
ab :package: 📦
ab :e-mail: 📧
ab :incoming_envelope: 📨
ab :envelope_with_arrow: 📩
ab :mailbox_closed: 📪
ab :mailbox: 📫
ab :mailbox_with_mail: 📬
ab :mailbox_with_no_mail: 📭
ab :postbox: 📮
ab :postal_horn: 📯
ab :newspaper: 📰
ab :iphone: 📱
ab :calling: 📲
ab :vibration_mode: 📳
ab :mobile_phone_off: 📴
ab :no_mobile_phones: 📵
ab :signal_strength: 📶
ab :camera: 📷
ab :camera_with_flash: 📸
ab :video_camera: 📹
ab :tv: 📺
ab :radio: 📻
ab :vhs: 📼
ab :film_projector: 📽️
ab :prayer_beads: 📿
ab :twisted_rightwards_arrows: 🔀
ab :repeat: 🔁
ab :repeat_one: 🔂
ab :arrows_clockwise: 🔃
ab :arrows_counterclockwise: 🔄
ab :low_brightness: 🔅
ab :high_brightness: 🔆
ab :mute: 🔇
ab :speaker: 🔈
ab :sound: 🔉
ab :loud_sound: 🔊
ab :battery: 🔋
ab :electric_plug: 🔌
ab :mag: 🔍
ab :mag_right: 🔎
ab :lock_with_ink_pen: 🔏
ab :closed_lock_with_key: 🔐
ab :key: 🔑
ab :lock: 🔒
ab :unlock: 🔓
ab :bell: 🔔
ab :no_bell: 🔕
ab :bookmark: 🔖
ab :link: 🔗
ab :radio_button: 🔘
ab :back: 🔙
ab :end: 🔚
ab :on: 🔛
ab :soon: 🔜
ab :top: 🔝
ab :underage: 🔞
ab :keycap_ten: 🔟
ab :capital_abcd: 🔠
ab :abcd: 🔡
ab :1234: 🔢
ab :symbols: 🔣
ab :abc: 🔤
ab :fire: 🔥
ab :flashlight: 🔦
ab :wrench: 🔧
ab :hammer: 🔨
ab :nut_and_bolt: 🔩
ab :hocho: 🔪
ab :gun: 🔫
ab :microscope: 🔬
ab :telescope: 🔭
ab :crystal_ball: 🔮
ab :six_pointed_star: 🔯
ab :beginner: 🔰
ab :trident: 🔱
ab :black_square_button: 🔲
ab :white_square_button: 🔳
ab :red_circle: 🔴
ab :large_blue_circle: 🔵
ab :large_orange_diamond: 🔶
ab :large_blue_diamond: 🔷
ab :small_orange_diamond: 🔸
ab :small_blue_diamond: 🔹
ab :small_red_triangle: 🔺
ab :small_red_triangle_down: 🔻
ab :arrow_up_small: 🔼
ab :arrow_down_small: 🔽
ab :om_symbol: 🕉️
ab :dove_of_peace: 🕊️
ab :kaaba: 🕋
ab :mosque: 🕌
ab :synagogue: 🕍
ab :menorah_with_nine_branches: 🕎
ab :clock1: 🕐
ab :clock2: 🕑
ab :clock3: 🕒
ab :clock4: 🕓
ab :clock5: 🕔
ab :clock6: 🕕
ab :clock7: 🕖
ab :clock8: 🕗
ab :clock9: 🕘
ab :clock10: 🕙
ab :clock11: 🕚
ab :clock12: 🕛
ab :clock130: 🕜
ab :clock230: 🕝
ab :clock330: 🕞
ab :clock430: 🕟
ab :clock530: 🕠
ab :clock630: 🕡
ab :clock730: 🕢
ab :clock830: 🕣
ab :clock930: 🕤
ab :clock1030: 🕥
ab :clock1130: 🕦
ab :clock1230: 🕧
ab :candle: 🕯️
ab :mantelpiece_clock: 🕰️
ab :hole: 🕳️
ab :detective: 🕵️
ab :dark_sunglasses: 🕶️
ab :spider: 🕷️
ab :spider_web: 🕸️
ab :joystick: 🕹️
ab :linked_paperclips: 🖇️
ab :lower_left_ballpoint_pen: 🖊️
ab :lower_left_fountain_pen: 🖋️
ab :lower_left_paintbrush: 🖌️
ab :lower_left_crayon: 🖍️
ab :raised_hand_with_fingers_splayed: 🖐️
ab :middle_finger: 🖕
ab :spock-hand: 🖖
ab :black_heart: 🖤
ab :desktop_computer: 🖥️
ab :printer: 🖨️
ab :three_button_mouse: 🖱️
ab :trackball: 🖲️
ab :frame_with_picture: 🖼️
ab :card_index_dividers: 🗂️
ab :card_file_box: 🗃️
ab :file_cabinet: 🗄️
ab :wastebasket: 🗑️
ab :spiral_note_pad: 🗒️
ab :spiral_calendar_pad: 🗓️
ab :compression: 🗜️
ab :old_key: 🗝️
ab :rolled_up_newspaper: 🗞️
ab :dagger_knife: 🗡️
ab :speaking_head_in_silhouette: 🗣️
ab :left_speech_bubble: 🗨️
ab :right_anger_bubble: 🗯️
ab :ballot_box_with_ballot: 🗳️
ab :world_map: 🗺️
ab :mount_fuji: 🗻
ab :tokyo_tower: 🗼
ab :statue_of_liberty: 🗽
ab :japan: 🗾
ab :moyai: 🗿
ab :grinning: 😀
ab :grin: 😁
ab :joy: 😂
ab :smiley: 😃
ab :smile: 😄
ab :sweat_smile: 😅
ab :laughing: 😆
ab :innocent: 😇
ab :smiling_imp: 😈
ab :wink: 😉
ab :blush: 😊
ab :yum: 😋
ab :relieved: 😌
ab :heart_eyes: 😍
ab :sunglasses: 😎
ab :smirk: 😏
ab :neutral_face: 😐
ab :expressionless: 😑
ab :unamused: 😒
ab :sweat: 😓
ab :pensive: 😔
ab :confused: 😕
ab :confounded: 😖
ab :kissing: 😗
ab :kissing_heart: 😘
ab :kissing_smiling_eyes: 😙
ab :kissing_closed_eyes: 😚
ab :stuck_out_tongue: 😛
ab :stuck_out_tongue_winking_eye: 😜
ab :stuck_out_tongue_closed_eyes: 😝
ab :disappointed: 😞
ab :worried: 😟
ab :angry: 😠
ab :rage: 😡
ab :cry: 😢
ab :persevere: 😣
ab :triumph: 😤
ab :disappointed_relieved: 😥
ab :frowning: 😦
ab :anguished: 😧
ab :fearful: 😨
ab :weary: 😩
ab :sleepy: 😪
ab :tired_face: 😫
ab :grimacing: 😬
ab :sob: 😭
ab :open_mouth: 😮
ab :hushed: 😯
ab :cold_sweat: 😰
ab :scream: 😱
ab :astonished: 😲
ab :flushed: 😳
ab :sleeping: 😴
ab :dizzy_face: 😵
ab :no_mouth: 😶
ab :mask: 😷
ab :smile_cat: 😸
ab :joy_cat: 😹
ab :smiley_cat: 😺
ab :heart_eyes_cat: 😻
ab :smirk_cat: 😼
ab :kissing_cat: 😽
ab :pouting_cat: 😾
ab :crying_cat_face: 😿
ab :scream_cat: 🙀
ab :slightly_frowning_face: 🙁
ab :slightly_smiling_face: 🙂
ab :upside_down_face: 🙃
ab :face_with_rolling_eyes: 🙄
ab :no_good: 🙅
ab :bow: 🙇
ab :see_no_evil: 🙈
ab :hear_no_evil: 🙉
ab :speak_no_evil: 🙊
ab :raising_hand: 🙋
ab :raised_hands: 🙌
ab :person_frowning: 🙍
ab :person_with_pouting_face: 🙎
ab :pray: 🙏
ab :rocket: 🚀
ab :helicopter: 🚁
ab :steam_locomotive: 🚂
ab :railway_car: 🚃
ab :bullettrain_side: 🚄
ab :bullettrain_front: 🚅
ab :train2: 🚆
ab :metro: 🚇
ab :light_rail: 🚈
ab :station: 🚉
ab :tram: 🚊
ab :train: 🚋
ab :bus: 🚌
ab :oncoming_bus: 🚍
ab :trolleybus: 🚎
ab :busstop: 🚏
ab :minibus: 🚐
ab :ambulance: 🚑
ab :fire_engine: 🚒
ab :police_car: 🚓
ab :oncoming_police_car: 🚔
ab :taxi: 🚕
ab :oncoming_taxi: 🚖
ab :car: 🚗
ab :oncoming_automobile: 🚘
ab :blue_car: 🚙
ab :truck: 🚚
ab :articulated_lorry: 🚛
ab :tractor: 🚜
ab :monorail: 🚝
ab :mountain_railway: 🚞
ab :suspension_railway: 🚟
ab :mountain_cableway: 🚠
ab :aerial_tramway: 🚡
ab :ship: 🚢
ab :rowboat: 🚣
ab :speedboat: 🚤
ab :traffic_light: 🚥
ab :vertical_traffic_light: 🚦
ab :construction: 🚧
ab :rotating_light: 🚨
ab :triangular_flag_on_post: 🚩
ab :door: 🚪
ab :no_entry_sign: 🚫
ab :smoking: 🚬
ab :no_smoking: 🚭
ab :put_litter_in_its_place: 🚮
ab :do_not_litter: 🚯
ab :potable_water: 🚰
ab :non-potable_water: 🚱
ab :bike: 🚲
ab :no_bicycles: 🚳
ab :bicyclist: 🚴
ab :mountain_bicyclist: 🚵
ab :walking: 🚶
ab :no_pedestrians: 🚷
ab :children_crossing: 🚸
ab :mens: 🚹
ab :womens: 🚺
ab :restroom: 🚻
ab :baby_symbol: 🚼
ab :toilet: 🚽
ab :wc: 🚾
ab :shower: 🚿
ab :bath: 🛀
ab :bathtub: 🛁
ab :passport_control: 🛂
ab :customs: 🛃
ab :baggage_claim: 🛄
ab :left_luggage: 🛅
ab :couch_and_lamp: 🛋️
ab :sleeping_accommodation: 🛌
ab :shopping_bags: 🛍️
ab :bellhop_bell: 🛎️
ab :bed: 🛏️
ab :place_of_worship: 🛐
ab :octagonal_sign: 🛑
ab :shopping_trolley: 🛒
ab :hindu_temple: 🛕
ab :hut: 🛖
ab :elevator: 🛗
ab :wireless: 🛜
ab :playground_slide: 🛝
ab :wheel: 🛞
ab :ring_buoy: 🛟
ab :hammer_and_wrench: 🛠️
ab :shield: 🛡️
ab :oil_drum: 🛢️
ab :motorway: 🛣️
ab :railway_track: 🛤️
ab :motor_boat: 🛥️
ab :small_airplane: 🛩️
ab :airplane_departure: 🛫
ab :airplane_arriving: 🛬
ab :satellite: 🛰️
ab :passenger_ship: 🛳️
ab :scooter: 🛴
ab :motor_scooter: 🛵
ab :canoe: 🛶
ab :sled: 🛷
ab :flying_saucer: 🛸
ab :skateboard: 🛹
ab :auto_rickshaw: 🛺
ab :pickup_truck: 🛻
ab :roller_skate: 🛼
ab :large_orange_circle: 🟠
ab :large_yellow_circle: 🟡
ab :large_green_circle: 🟢
ab :large_purple_circle: 🟣
ab :large_brown_circle: 🟤
ab :large_red_square: 🟥
ab :large_blue_square: 🟦
ab :large_orange_square: 🟧
ab :large_yellow_square: 🟨
ab :large_green_square: 🟩
ab :large_purple_square: 🟪
ab :large_brown_square: 🟫
ab :heavy_equals_sign: 🟰
ab :pinched_fingers: 🤌
ab :white_heart: 🤍
ab :brown_heart: 🤎
ab :pinching_hand: 🤏
ab :zipper_mouth_face: 🤐
ab :money_mouth_face: 🤑
ab :face_with_thermometer: 🤒
ab :nerd_face: 🤓
ab :thinking_face: 🤔
ab :face_with_head_bandage: 🤕
ab :robot_face: 🤖
ab :hugging_face: 🤗
ab :the_horns: 🤘
ab :call_me_hand: 🤙
ab :raised_back_of_hand: 🤚
ab :left-facing_fist: 🤛
ab :right-facing_fist: 🤜
ab :handshake: 🤝
ab :crossed_fingers: 🤞
ab :i_love_you_hand_sign: 🤟
ab :face_with_cowboy_hat: 🤠
ab :clown_face: 🤡
ab :nauseated_face: 🤢
ab :rolling_on_the_floor_laughing: 🤣
ab :drooling_face: 🤤
ab :lying_face: 🤥
ab :face_palm: 🤦
ab :sneezing_face: 🤧
ab :face_with_raised_eyebrow: 🤨
ab :star-struck: 🤩
ab :zany_face: 🤪
ab :shushing_face: 🤫
ab :face_with_symbols_on_mouth: 🤬
ab :face_with_hand_over_mouth: 🤭
ab :face_vomiting: 🤮
ab :exploding_head: 🤯
ab :breast-feeding: 🤱
ab :palms_up_together: 🤲
ab :selfie: 🤳
ab :prince: 🤴
ab :person_in_tuxedo: 🤵
ab :mrs_claus: 🤶
ab :shrug: 🤷
ab :person_doing_cartwheel: 🤸
ab :juggling: 🤹
ab :fencer: 🤺
ab :wrestlers: 🤼
ab :water_polo: 🤽
ab :handball: 🤾
ab :diving_mask: 🤿
ab :wilted_flower: 🥀
ab :drum_with_drumsticks: 🥁
ab :clinking_glasses: 🥂
ab :tumbler_glass: 🥃
ab :spoon: 🥄
ab :goal_net: 🥅
ab :first_place_medal: 🥇
ab :second_place_medal: 🥈
ab :third_place_medal: 🥉
ab :boxing_glove: 🥊
ab :martial_arts_uniform: 🥋
ab :curling_stone: 🥌
ab :lacrosse: 🥍
ab :softball: 🥎
ab :flying_disc: 🥏
ab :croissant: 🥐
ab :avocado: 🥑
ab :cucumber: 🥒
ab :bacon: 🥓
ab :potato: 🥔
ab :carrot: 🥕
ab :baguette_bread: 🥖
ab :green_salad: 🥗
ab :shallow_pan_of_food: 🥘
ab :stuffed_flatbread: 🥙
ab :egg: 🥚
ab :glass_of_milk: 🥛
ab :peanuts: 🥜
ab :kiwifruit: 🥝
ab :pancakes: 🥞
ab :dumpling: 🥟
ab :fortune_cookie: 🥠
ab :takeout_box: 🥡
ab :chopsticks: 🥢
ab :bowl_with_spoon: 🥣
ab :cup_with_straw: 🥤
ab :coconut: 🥥
ab :broccoli: 🥦
ab :pie: 🥧
ab :pretzel: 🥨
ab :cut_of_meat: 🥩
ab :sandwich: 🥪
ab :canned_food: 🥫
ab :leafy_green: 🥬
ab :mango: 🥭
ab :moon_cake: 🥮
ab :bagel: 🥯
ab :smiling_face_with_3_hearts: 🥰
ab :yawning_face: 🥱
ab :smiling_face_with_tear: 🥲
ab :partying_face: 🥳
ab :woozy_face: 🥴
ab :hot_face: 🥵
ab :cold_face: 🥶
ab :ninja: 🥷
ab :disguised_face: 🥸
ab :face_holding_back_tears: 🥹
ab :pleading_face: 🥺
ab :sari: 🥻
ab :lab_coat: 🥼
ab :goggles: 🥽
ab :hiking_boot: 🥾
ab :womans_flat_shoe: 🥿
ab :crab: 🦀
ab :lion_face: 🦁
ab :scorpion: 🦂
ab :turkey: 🦃
ab :unicorn_face: 🦄
ab :eagle: 🦅
ab :duck: 🦆
ab :bat: 🦇
ab :shark: 🦈
ab :owl: 🦉
ab :fox_face: 🦊
ab :butterfly: 🦋
ab :deer: 🦌
ab :gorilla: 🦍
ab :lizard: 🦎
ab :rhinoceros: 🦏
ab :shrimp: 🦐
ab :squid: 🦑
ab :giraffe_face: 🦒
ab :zebra_face: 🦓
ab :hedgehog: 🦔
ab :sauropod: 🦕
ab :t-rex: 🦖
ab :cricket: 🦗
ab :kangaroo: 🦘
ab :llama: 🦙
ab :peacock: 🦚
ab :hippopotamus: 🦛
ab :parrot: 🦜
ab :raccoon: 🦝
ab :lobster: 🦞
ab :mosquito: 🦟
ab :microbe: 🦠
ab :badger: 🦡
ab :swan: 🦢
ab :mammoth: 🦣
ab :dodo: 🦤
ab :sloth: 🦥
ab :otter: 🦦
ab :orangutan: 🦧
ab :skunk: 🦨
ab :flamingo: 🦩
ab :oyster: 🦪
ab :beaver: 🦫
ab :bison: 🦬
ab :seal: 🦭
ab :guide_dog: 🦮
ab :probing_cane: 🦯
ab :bone: 🦴
ab :leg: 🦵
ab :foot: 🦶
ab :tooth: 🦷
ab :superhero: 🦸
ab :supervillain: 🦹
ab :safety_vest: 🦺
ab :ear_with_hearing_aid: 🦻
ab :motorized_wheelchair: 🦼
ab :manual_wheelchair: 🦽
ab :mechanical_arm: 🦾
ab :mechanical_leg: 🦿
ab :cheese_wedge: 🧀
ab :cupcake: 🧁
ab :salt: 🧂
ab :beverage_box: 🧃
ab :garlic: 🧄
ab :onion: 🧅
ab :falafel: 🧆
ab :waffle: 🧇
ab :butter: 🧈
ab :mate_drink: 🧉
ab :ice_cube: 🧊
ab :bubble_tea: 🧋
ab :troll: 🧌
ab :standing_person: 🧍
ab :kneeling_person: 🧎
ab :deaf_person: 🧏
ab :face_with_monocle: 🧐
ab :adult: 🧑
ab :child: 🧒
ab :older_adult: 🧓
ab :bearded_person: 🧔
ab :person_with_headscarf: 🧕
ab :person_in_steamy_room: 🧖
ab :person_climbing: 🧗
ab :person_in_lotus_position: 🧘
ab :mage: 🧙
ab :fairy: 🧚
ab :vampire: 🧛
ab :merperson: 🧜
ab :elf: 🧝
ab :genie: 🧞
ab :zombie: 🧟
ab :brain: 🧠
ab :orange_heart: 🧡
ab :billed_cap: 🧢
ab :scarf: 🧣
ab :gloves: 🧤
ab :coat: 🧥
ab :socks: 🧦
ab :red_envelope: 🧧
ab :firecracker: 🧨
ab :jigsaw: 🧩
ab :test_tube: 🧪
ab :petri_dish: 🧫
ab :dna: 🧬
ab :compass: 🧭
ab :abacus: 🧮
ab :fire_extinguisher: 🧯
ab :toolbox: 🧰
ab :bricks: 🧱
ab :magnet: 🧲
ab :luggage: 🧳
ab :lotion_bottle: 🧴
ab :thread: 🧵
ab :yarn: 🧶
ab :safety_pin: 🧷
ab :teddy_bear: 🧸
ab :broom: 🧹
ab :basket: 🧺
ab :roll_of_paper: 🧻
ab :soap: 🧼
ab :sponge: 🧽
ab :receipt: 🧾
ab :nazar_amulet: 🧿
ab :ballet_shoes: 🩰
ab :one-piece_swimsuit: 🩱
ab :briefs: 🩲
ab :shorts: 🩳
ab :thong_sandal: 🩴
ab :light_blue_heart: 🩵
ab :grey_heart: 🩶
ab :pink_heart: 🩷
ab :drop_of_blood: 🩸
ab :adhesive_bandage: 🩹
ab :stethoscope: 🩺
ab :x-ray: 🩻
ab :crutch: 🩼
ab :yo-yo: 🪀
ab :kite: 🪁
ab :parachute: 🪂
ab :boomerang: 🪃
ab :magic_wand: 🪄
ab :pinata: 🪅
ab :nesting_dolls: 🪆
ab :maracas: 🪇
ab :flute: 🪈
ab :ringed_planet: 🪐
ab :chair: 🪑
ab :razor: 🪒
ab :axe: 🪓
ab :diya_lamp: 🪔
ab :banjo: 🪕
ab :military_helmet: 🪖
ab :accordion: 🪗
ab :long_drum: 🪘
ab :coin: 🪙
ab :carpentry_saw: 🪚
ab :screwdriver: 🪛
ab :ladder: 🪜
ab :hook: 🪝
ab :mirror: 🪞
ab :window: 🪟
ab :plunger: 🪠
ab :sewing_needle: 🪡
ab :knot: 🪢
ab :bucket: 🪣
ab :mouse_trap: 🪤
ab :toothbrush: 🪥
ab :headstone: 🪦
ab :placard: 🪧
ab :rock: 🪨
ab :mirror_ball: 🪩
ab :identification_card: 🪪
ab :low_battery: 🪫
ab :hamsa: 🪬
ab :folding_hand_fan: 🪭
ab :hair_pick: 🪮
ab :khanda: 🪯
ab :fly: 🪰
ab :worm: 🪱
ab :beetle: 🪲
ab :cockroach: 🪳
ab :potted_plant: 🪴
ab :wood: 🪵
ab :feather: 🪶
ab :lotus: 🪷
ab :coral: 🪸
ab :empty_nest: 🪹
ab :nest_with_eggs: 🪺
ab :hyacinth: 🪻
ab :jellyfish: 🪼
ab :wing: 🪽
ab :goose: 🪿
ab :anatomical_heart: 🫀
ab :lungs: 🫁
ab :people_hugging: 🫂
ab :pregnant_person: 🫄
ab :person_with_crown: 🫅
ab :moose: 🫎
ab :donkey: 🫏
ab :blueberries: 🫐
ab :bell_pepper: 🫑
ab :olive: 🫒
ab :flatbread: 🫓
ab :tamale: 🫔
ab :fondue: 🫕
ab :teapot: 🫖
ab :pouring_liquid: 🫗
ab :beans: 🫘
ab :jar: 🫙
ab :ginger_root: 🫚
ab :pea_pod: 🫛
ab :melting_face: 🫠
ab :saluting_face: 🫡
ab :face_with_open_eyes_and_hand_over_mouth: 🫢
ab :face_with_peeking_eye: 🫣
ab :face_with_diagonal_mouth: 🫤
ab :dotted_line_face: 🫥
ab :biting_lip: 🫦
ab :bubbles: 🫧
ab :shaking_face: 🫨
ab :hand_with_index_finger_and_thumb_crossed: 🫰
ab :rightwards_hand: 🫱
ab :leftwards_hand: 🫲
ab :palm_down_hand: 🫳
ab :palm_up_hand: 🫴
ab :index_pointing_at_the_viewer: 🫵
ab :heart_hands: 🫶
ab :leftwards_pushing_hand: 🫷
ab :rightwards_pushing_hand: 🫸
ab :bangbang: ‼️
ab :interrobang: ⁉️
ab :tm: ™️
ab :information_source: ℹ️
ab :left_right_arrow: ↔️
ab :arrow_up_down: ↕️
ab :arrow_upper_left: ↖️
ab :arrow_upper_right: ↗️
ab :arrow_lower_right: ↘️
ab :arrow_lower_left: ↙️
ab :leftwards_arrow_with_hook: ↩️
ab :arrow_right_hook: ↪️
ab :watch: ⌚
ab :hourglass: ⌛
ab :keyboard: ⌨️
ab :eject: ⏏️
ab :fast_forward: ⏩
ab :rewind: ⏪
ab :arrow_double_up: ⏫
ab :arrow_double_down: ⏬
ab :player_next: ⏭️
ab :player_previous: ⏮️
ab :player_pause: ⏯️
ab :alarm_clock: ⏰
ab :stopwatch: ⏱️
ab :timer_clock: ⏲️
ab :hourglass_flowing_sand: ⏳
ab :double_vertical_bar: ⏸️
ab :player_stop: ⏹️
ab :player_record: ⏺️
ab :m: Ⓜ️
ab :black_small_square: ▪️
ab :white_small_square: ▫️
ab :arrow_forward: ▶️
ab :arrow_backward: ◀️
ab :white_medium_square: ◻️
ab :black_medium_square: ◼️
ab :white_medium_small_square: ◽
ab :black_medium_small_square: ◾
ab :sunny: ☀️
ab :cloud: ☁️
ab :umbrella: ☂️
ab :snowman: ☃️
ab :comet: ☄️
ab :phone: ☎️
ab :ballot_box_with_check: ☑️
ab :umbrella_with_rain_drops: ☔
ab :coffee: ☕
ab :shamrock: ☘️
ab :point_up: ☝️
ab :skull_and_crossbones: ☠️
ab :radioactive_sign: ☢️
ab :biohazard_sign: ☣️
ab :orthodox_cross: ☦️
ab :star_and_crescent: ☪️
ab :peace_symbol: ☮️
ab :yin_yang: ☯️
ab :wheel_of_dharma: ☸️
ab :white_frowning_face: ☹️
ab :relaxed: ☺️
ab :female_sign: ♀️
ab :male_sign: ♂️
ab :aries: ♈
ab :taurus: ♉
ab :gemini: ♊
ab :cancer: ♋
ab :leo: ♌
ab :virgo: ♍
ab :libra: ♎
ab :scorpius: ♏
ab :sagittarius: ♐
ab :capricorn: ♑
ab :aquarius: ♒
ab :pisces: ♓
ab :chess_pawn: ♟️
ab :spades: ♠️
ab :clubs: ♣️
ab :hearts: ♥️
ab :diamonds: ♦️
ab :hotsprings: ♨️
ab :recycle: ♻️
ab :infinity: ♾️
ab :wheelchair: ♿
ab :hammer_and_pick: ⚒️
ab :anchor: ⚓
ab :crossed_swords: ⚔️
ab :medical_symbol: ⚕️
ab :scales: ⚖️
ab :alembic: ⚗️
ab :gear: ⚙️
ab :atom_symbol: ⚛️
ab :fleur_de_lis: ⚜️
ab :warning: ⚠️
ab :zap: ⚡
ab :transgender_symbol: ⚧️
ab :white_circle: ⚪
ab :black_circle: ⚫
ab :coffin: ⚰️
ab :funeral_urn: ⚱️
ab :soccer: ⚽
ab :baseball: ⚾
ab :snowman_without_snow: ⛄
ab :partly_sunny: ⛅
ab :thunder_cloud_and_rain: ⛈️
ab :ophiuchus: ⛎
ab :pick: ⛏️
ab :helmet_with_white_cross: ⛑️
ab :chains: ⛓️
ab :no_entry: ⛔
ab :shinto_shrine: ⛩️
ab :church: ⛪
ab :mountain: ⛰️
ab :umbrella_on_ground: ⛱️
ab :fountain: ⛲
ab :golf: ⛳
ab :ferry: ⛴️
ab :boat: ⛵
ab :skier: ⛷️
ab :ice_skate: ⛸️
ab :person_with_ball: ⛹️
ab :tent: ⛺
ab :fuelpump: ⛽
ab :scissors: ✂️
ab :white_check_mark: ✅
ab :airplane: ✈️
ab :email: ✉️
ab :fist: ✊
ab :hand: ✋
ab :v: ✌️
ab :writing_hand: ✍️
ab :pencil2: ✏️
ab :black_nib: ✒️
ab :heavy_check_mark: ✔️
ab :heavy_multiplication_x: ✖️
ab :latin_cross: ✝️
ab :star_of_david: ✡️
ab :sparkles: ✨
ab :eight_spoked_asterisk: ✳️
ab :eight_pointed_black_star: ✴️
ab :snowflake: ❄️
ab :sparkle: ❇️
ab :x: ❌
ab :negative_squared_cross_mark: ❎
ab :question: ❓
ab :grey_question: ❔
ab :grey_exclamation: ❕
ab :exclamation: ❗
ab :heavy_heart_exclamation_mark_ornament: ❣️
ab :heart: ❤️
ab :heavy_plus_sign: ➕
ab :heavy_minus_sign: ➖
ab :heavy_division_sign: ➗
ab :arrow_right: ➡️
ab :curly_loop: ➰
ab :loop: ➿
ab :arrow_heading_up: ⤴️
ab :arrow_heading_down: ⤵️
ab :arrow_left: ⬅️
ab :arrow_up: ⬆️
ab :arrow_down: ⬇️
ab :black_large_square: ⬛
ab :white_large_square: ⬜
ab :star: ⭐
ab :o: ⭕
ab :wavy_dash: 〰️
ab :part_alternation_mark: 〽️
ab :congratulations: ㊗️
ab :secret: ㊙️

iab ife if err != nil {<CR><tab>return err<CR>}<CR>
